In [1]:
import pandas as pd

In [2]:
data = pd.DataFrame({
    "Category": ["Furniture", "Technology", "Furniture", "Technology", "Office"],
    "Sales": [1000, 2000, 1500, 3000, 800]
})
data

     Category  Sales
0   Furniture   1000
1  Technology   2000
2   Furniture   1500
3  Technology   3000
4      Office    800

In [3]:
data['Category']

0     Furniture
1    Technology
2     Furniture
3    Technology
4        Office
Name: Category, dtype: object

In [5]:
data.groupby('Category')['Sales'].sum()

Category
Furniture     2500
Office         800
Technology    5000
Name: Sales, dtype: int64

In [6]:
data.groupby('Category')['Sales'].mean()

Category
Furniture     1250.0
Office         800.0
Technology    2500.0
Name: Sales, dtype: float64

In [7]:
data.groupby('Category')['Sales'].max()

Category
Furniture     1500
Office         800
Technology    3000
Name: Sales, dtype: int64

In [8]:
data.groupby('Category')['Sales'].count()

Category
Furniture     2
Office        1
Technology    2
Name: Sales, dtype: int64

In [12]:


data2 = pd.DataFrame({
    "Department": ["IT", "HR", "IT", "Finance", "HR", "Finance", "IT", "HR", "Finance", "IT"],
    "Employee": ["Alice", "Bob", "Charlie", "David", "Eva", "Frank", "Grace", "Helen", "Ian", "Jack"],
    "Salary": [60000, 45000, 70000, 55000, 50000, 65000, 72000, 48000, 60000, 68000],
    "Marks": [88, 75, 92, 81, 79, 85, 95, 77, 83, 90],
    "Profit": [5000, 3000, 7000, 4000, 3500, 6000, 8000, 3200, 5500, 7500],
    "Region": ["North", "South", "North", "East", "South", "East", "West", "South", "East", "West"],
    "City": ["Delhi", "Mumbai", "Delhi", "Kolkata", "Mumbai", "Kolkata", "Pune", "Mumbai", "Kolkata", "Pune"],
    "Category": ["Laptop", "Chair", "Laptop", "Table", "Chair", "Table", "Laptop", "Chair", "Table", "Laptop"],
    "Price": [800, 150, 900, 250, 180, 300, 950, 170, 280, 920],
    "Year": [2023, 2023, 2023, 2024, 2024, 2024, 2023, 2024, 2023, 2024],
    "Quarter": ["Q1", "Q2", "Q3", "Q1", "Q2", "Q3", "Q4", "Q4", "Q1", "Q2"]
})
data2

,Department,Employee,Salary,Marks,Profit,Region,City,Category,Price,Year,Quarter
0,IT,Alice,60000,88,5000,North,Delhi,Laptop,800,2023,Q1
1,HR,Bob,45000,75,3000,South,Mumbai,Chair,150,2023,Q2
2,IT,Charlie,70000,92,7000,North,Delhi,Laptop,900,2023,Q3
3,Finance,David,55000,81,4000,East,Kolkata,Table,250,2024,Q1
4,HR,Eva,50000,79,3500,South,Mumbai,Chair,180,2024,Q2
5,Finance,Frank,65000,85,6000,East,Kolkata,Table,300,2024,Q3
6,IT,Grace,72000,95,8000,West,Pune,Laptop,950,2023,Q4
7,HR,Helen,48000,77,3200,South,Mumbai,Chair,170,2024,Q4
8,Finance,Ian,60000,83,5500,East,Kolkata,Table,280,2023,Q1
9,IT,Jack,68000,90,7500,West,Pune,Laptop,920,2024,Q2

In [13]:
data2.groupby("Department")['Salary'].sum()

Department
Finance    180000
HR         143000
IT         270000
Name: Salary, dtype: int64

In [15]:
data2.groupby("Department")['Marks'].mean()

Department
Finance    83.00
HR         77.00
IT         91.25
Name: Marks, dtype: float64

In [16]:
data2.groupby("Department")['Salary'].max()

Department
Finance    65000
HR         50000
IT         72000
Name: Salary, dtype: int64

In [20]:
data2.groupby("Department")['Department'].count()

Department
Finance    3
HR         3
IT         4
Name: Department, dtype: int64

In [21]:
data2.groupby("Region")['Profit'].sum()

Region
East     15500
North    12000
South     9700
West     15500
Name: Profit, dtype: int64

In [22]:
data2.groupby("Category")['Price'].mean()

Category
Chair     166.666667
Laptop    892.500000
Table     276.666667
Name: Price, dtype: float64

In [23]:
data2.groupby("City")['Marks'].max()

City
Delhi      92
Kolkata    85
Mumbai     79
Pune       95
Name: Marks, dtype: int64

In [24]:
data2.groupby("Region")['Profit'].min()

Region
East     4000
North    5000
South    3000
West     7500
Name: Profit, dtype: int64

In [27]:
data2.groupby("City")['Employee'].count()

City
Delhi      2
Kolkata    3
Mumbai     3
Pune       2
Name: Employee, dtype: int64

In [28]:
data2.groupby("Year")['Salary'].sum()

Year
2023    307000
2024    286000
Name: Salary, dtype: int64

In [29]:
data2.groupby(["Year" , "Quarter"])['Salary'].sum()

Year  Quarter
2023  Q1         120000
      Q2          45000
      Q3          70000
      Q4          72000
2024  Q1          55000
      Q2         118000
      Q3          65000
      Q4          48000
Name: Salary, dtype: int64

In [30]:
data2.groupby(["Region" , "Year"])['Profit'].mean()

Region  Year
East    2023    5500.0
        2024    5000.0
North   2023    6000.0
South   2023    3000.0
        2024    3350.0
West    2023    8000.0
        2024    7500.0
Name: Profit, dtype: float64

In [31]:
data2.groupby(["Category" , "Year"])['Price'].max()

Category  Year
Chair     2023    150
          2024    180
Laptop    2023    950
          2024    920
Table     2023    280
          2024    300
Name: Price, dtype: int64

In [32]:
data2.groupby("Department")["Salary"].sum()

Department
Finance    180000
HR         143000
IT         270000
Name: Salary, dtype: int64

In [33]:
data2.groupby("Department")["Salary"].agg(
    ["sum", "mean", "max", "min", "count"]
)

               sum          mean    max    min  count
Department
Finance     180000  60000.000000  65000  55000      3
HR          143000  47666.666667  50000  45000      3
IT          270000  67500.000000  72000  60000      4

In [34]:
data2.groupby("Department").agg({
    "Salary": "sum",
    "Marks": "mean",
    "Profit": "max"
})

            Salary  Marks  Profit
Department
Finance     180000  83.00    6000
HR          143000  77.00    3500
IT          270000  91.25    8000

In [35]:
data2.groupby("Department").agg({
    "Salary": ["sum", "mean"],
    "Profit": ["max", "min"]
})

            Salary               Profit
               sum          mean    max   min
Department
Finance     180000  60000.000000   6000  4000
HR          143000  47666.666667   3500  3000
IT          270000  67500.000000   8000  5000